#ifndef _COLOR_H_
#define _COLOR_H_

namespace alphaone
{

#define GET_COLOR_CODE(NUM) "\e[" #NUM "m"
#define FORE_RESET GET_COLOR_CODE(39)
#define FORE_BLACK GET_COLOR_CODE(30)
#define FORE_RED GET_COLOR_CODE(31)
#define FORE_GREEN GET_COLOR_CODE(32)
#define FORE_YELLOW GET_COLOR_CODE(33)
#define FORE_BLUE GET_COLOR_CODE(34)
#define FORE_MAGENTA GET_COLOR_CODE(35)
#define FORE_CYAN GET_COLOR_CODE(36)
#define FORE_LIGHT_GRAY GET_COLOR_CODE(37)
#define FORE_DARK_GRAY GET_COLOR_CODE(90)
#define FORE_LIGHT_RED GET_COLOR_CODE(91)
#define FORE_LIGHT_GREEN GET_COLOR_CODE(92)
#define FORE_LIGHT_YELLOW GET_COLOR_CODE(93)
#define FORE_LIGHT_BLUE GET_COLOR_CODE(94)
#define FORE_LIGHT_MAGENTA GET_COLOR_CODE(95)
#define FORE_LIGHT_CYAN GET_COLOR_CODE(96)
#define FORE_WHITE GET_COLOR_CODE(97)

#define BACK_RESET GET_COLOR_CODE(49)
#define BACK_BLACK GET_COLOR_CODE(40)
#define BACK_RED GET_COLOR_CODE(41)
#define BACK_GREEN GET_COLOR_CODE(42)
#define BACK_YELLOW GET_COLOR_CODE(43)
#define BACK_BLUE GET_COLOR_CODE(44)
#define BACK_MAGENTA GET_COLOR_CODE(45)
#define BACK_CYAN GET_COLOR_CODE(46)
#define BACK_LIGHT_GRAY GET_COLOR_CODE(47)
#define BACK_DARK_GRAY GET_COLOR_CODE(100)
#define BACK_LIGHT_RED GET_COLOR_CODE(101)
#define BACK_LIGHT_GREEN GET_COLOR_CODE(102)
#define BACK_LIGHT_YELLOW GET_COLOR_CODE(103)
#define BACK_LIGHT_BLUE GET_COLOR_CODE(104)
#define BACK_LIGHT_MAGENTA GET_COLOR_CODE(105)
#define BACK_LIGHT_CYAN GET_COLOR_CODE(106)
#define BACK_WHITE GET_COLOR_CODE(107)


}  // namespace alphaone


#endif