{
 "title": "Alexandex",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total volumn",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_exchange",
     "query": "SELECT sum(\"trade_volume\") FROM \"pnl\" WHERE $timeFilter GROUP BY exchange, time($__interval)"
    }
   ]
  },
  {
   "title": "NAV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expression": "$C+$D", "reducer": "mean", "type": "math" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Account Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "balance-$tag_exchange",
     "groupBy": [
      { "params": [ "exchange::tag" ], "type": "tag" }
     ],
     "measurement": "account",
     "query": "SELECT \"balance\" FROM \"account\" WHERE $timeFilter GROUP BY \"exchange\"::tag",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "margin-$tag_exchange",
     "groupBy": [
      { "params": [ "exchange::tag" ], "type": "tag" }
     ],
     "measurement": "account",
     "query": "SELECT last(\"balance\") FROM \"account\" WHERE (\"exchange\"::tag = 'binance') AND $timeFilter",
     "select": [
      [
       { "params": [ "margin" ], "type": "field" }
      ]
     ]
    },
    { "expression": "$C+$D", "reducer": "mean", "type": "math" }
   ]
  },
  {
   "title": "Margin usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "exchange::tag" ], "type": "tag" }
     ],
     "measurement": "account",
     "query": "SELECT (1 - (last(\"margin\") / last(\"balance\")))  AS \"margin_balance_ratio\" FROM \"account\" WHERE $timeFilter GROUP BY \"exchange\",  time(15s)\n",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "exchange::tag", "operator": "=", "value": "binance" }
     ]
    }
   ]
  },
  {
   "title": "Realized_profit (by symbol)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "$tag_symbol($tag_exchange)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pnl",
     "query": "SELECT sum(\"real_profit\") FROM \"pnl\" WHERE $timeFilter GROUP BY time(5m), exchange, symbol",
     "select": [
      [
       { "params": [ "trade_volume" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trading Volumn",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "alias": "$tag_symbol($tag_exchange)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pnl",
     "query": "SELECT sum(\"trade_volume\") FROM \"pnl\" WHERE $timeFilter GROUP BY time(5m), exchange, symbol",
     "select": [
      [
       { "params": [ "trade_volume" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Realized_profit (by strategy)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "$tag_job",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pnl",
     "query": "SELECT sum(\"real_profit\") FROM \"pnl\" WHERE $timeFilter GROUP BY time(5m), job",
     "select": [
      [
       { "params": [ "trade_volume" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trading Volumn (by strategy)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "alias": "$tag_job($tag_exchange)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pnl",
     "query": "SELECT sum(\"trade_volume\") FROM \"pnl\" WHERE $timeFilter GROUP BY time(5m), exchange, job",
     "select": [
      [
       { "params": [ "trade_volume" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "commission (by strategy)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "alias": "$tag_job",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pnl",
     "query": "SELECT sum(\"commission\") FROM \"pnl\" WHERE $timeFilter GROUP BY time(5m), job",
     "select": [
      [
       { "params": [ "trade_volume" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}