BINANCE = "binance"
UPERP = "UPERP"
CRYPTO = "CRYPTO"
CANDIDATE = "CANDIDATE"

CANDIDATE_POOL = [

    ("SmrcExpStrategy", "SMRCEXP_LINK_30m_8731_candidate", BINANCE, UPERP, "LINKUSDT_UPERP", CRYPTO),

]